language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn test
  - yarn build
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: $HEROKU_TOKEN
